ECommerceSystem.MVC/Controllers/CustomerController.cs
using ECommerceSystem.Core.Interfaces;
using ECommerceSystem.Core.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ECommerceSystem.MVC.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAction(LoginViewModel customerDetails)
        {
            if (ModelState.IsValid)
            {
                var customer = await _customerService.Login(customerDetails);
                if (customer != null)
                {
                    HttpContext.Session.SetString("UserId", customer.CustomerID);
                    HttpContext.Session.SetString("Email", customer.Email);
                    ViewBag.message = "You Logged In Successfully";
                    return RedirectToAction("Index", "Home");
                }
            }
            ViewBag.message = "Invalid Login Details, try Again";
            return View("Login", customerDetails);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RegisterAction(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                var added = await _customerService.Register(customer);
                if (added != null)
                {
                    ViewBag.message = "Registration Successfully";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.message = "Email Already Exist";
                    return View("Register", customer);
                }
            }
            ViewBag.message = "Ohh something went wrong, Try Again!";
            return View("Register", customer);
        }
    }
}

ECommerceSystem.MVC/Controllers/HomeController.cs
using ECommerce.Models;
using ECommerceSystem.Core.Interfaces;
using ECommerceSystem.Domain.Model;
using ECommerceSystem.MVC.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;

        public HomeController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index()
        {
            ProductListViewModel productListViewModel = new ProductListViewModel();
            productListViewModel.Products = await _productRepository.GetAllProducts() != null? await _productRepository.GetAllProducts(): new List<ProductModel>();
            productListViewModel.CurrentCategory = _categoryRepository.GetAllCategories();
            return View(productListViewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerceSystem.MVC/Controllers/ProductController.cs
using ECommerceSystem.Core.Interfaces;
using ECommerceSystem.MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ECommerceSystem.MVC.Controllers
{
    public class ProductController : Controller
    {
       
        private readonly IProductRepository _productRepository;
        private readonly IProductService _productService;
        private readonly ICategoryRepository _categoryRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IProductService productService)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _productService = productService;
        }

        public async Task<IActionResult> ProductList(string id)
        {
            ProductListViewModel productListViewModel = new ProductListViewModel();
            productListViewModel.Products = await _productRepository.GetAllProducts();
            productListViewModel.currentProduct = await _productRepository.GetProductById(id);
            productListViewModel.CurrentCategory = _categoryRepository.GetAllCategories();
            productListViewModel.currentProductCategory = productListViewModel.currentProduct.Category;
            productListViewModel.AllRelatedProductsByCategory = await _productRepository.GetProductsByCategory(id);
            return View(productListViewModel);
        }

        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> StoreProduct(ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                if (product.ImageGallery != null)
                {
                    var storeProduct = await _productService.AddProduct(product);
                    if (storeProduct != null)
                    {
                        ViewBag.message = "Added Successfully";
                        return RedirectToAction("AddProduct");
                    }
                    else
                    {
                        ViewBag.message = "Product Insert UnSuccessful";
                        return View("AddProduct", product);
                    } 
                }
            }
            ViewBag.message = "Fill In The Details Properly";
            return View("AddProduct", product);
        }
    }
}

ECommerceSystem.MVC/Views/Customer/Login.cshtml
@model LoginViewModel
<div class="customer-container">
      <div class="row justify-content-center">
          <div class="col-md-5">
               <div class="card">
                 <h2 class="card-title text-center">Login</h2>
                  <div class="card-body py-md-4">
                   <form asp-action="LoginAction" method="post" enctype="multipart/form-data">
                       <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input asp-for="Email" class="form-control" placeholder="Email"/>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Password"/>
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                        <div class="d-flex flex-row align-items-center justify-content-between">
                          <a asp-controller="Customer" asp-action="Register" asp-route-id="">Register</a>
                          <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                        <div style="color: red;">@ViewBag.message</div>
                   </form>
                 </div>
              </div>
        </div>
    </div>
</div>

ECommerceSystem.MVC/Views/Customer/Register.cshtml
@model CustomerViewModel

<div class="customer-container">
      <div class="row justify-content-center">
          <div class="col-md-5">
               <div class="card">
                 <h2 class="card-title text-center">Register</h2>
                  <div class="card-body py-md-4">
                   <form asp-action="RegisterAction" method="post" enctype="multipart/form-data">
                       <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row_clearfix">
                            <div class="col_half">
                                <div> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                <input asp-for="FirstName" class="form-control"  placeholder="First Name" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col_half">
                                <div> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                <input asp-for="LastName" class="form-control" placeholder="Last Name" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input asp-for="Email" class="form-control"  placeholder="Email" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="Mobile"  class="form-control"  placeholder="Mobile"/>
                            <span asp-validation-for="Mobile" class="text-danger"></span>
                        </div>
                        <div class="row_clearfix">
                            <div class="col_half">
                                <div> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                <input asp-for="Password" type="password" class="form-control" placeholder="Password" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col_half">
                                <div> <span><i aria-hidden="true" class="fa fa-user"></i></span>
                                <input  asp-for="PasswordAgain" type="password" class="form-control"  placeholder="confirm-password"/>
                                <span asp-validation-for="PasswordAgain" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input asp-for="ImageUrl" multiple/>
                            <span asp-validation-for="ImageUrl" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="ShippingAddress"  class="form-control"  placeholder="Address"/>
                            <span asp-validation-for="ShippingAddress" class="text-danger"></span>
                        </div>

                        <div class="d-flex flex-row align-items-center justify-content-between">
                          <a asp-controller="Customer" asp-action="Login" asp-route-id="">Login</a>
                          <button class="btn btn-primary">Create Account</button>
                        </div>
                        <div style="color: red;">@ViewBag.message</div>
                   </form>
                 </div>
              </div>
        </div>
    </div>
</div>

ECommerceSystem.MVC/Views/Home/Index.cshtml
@model ProductListViewModel
@{
    ViewData["Title"] = "Home Page";
}

<section class="hero">
    <h1>
        Super flash sale <br>
        50% off
    </h1>
</section>

<!-- Product Display on Banner -->
<div class="container">
    <section class="top-product">
        @foreach(var product in Model.Products.OrderBy(x=> Guid.NewGuid()).Take(3))
        {
            <a asp-controller="Product" asp-action="ProductList" asp-route-id="@product.ProductId">
            <div class="top-product-container">
                <img src="./ProductImages/@product.productImageModel.First().imageName" class="other-product-image" />
                <h2 class="product-heading">@product.ProductName</h2>
                <div class="top-product-below-price">
                    <p class="top-product-actual-price">@product.Price.ToString("C")</p>
                    <h6 class="top-product-per-off">@product.PercentageOff %Off</h6>
                    <h6 class="top-product-discount-price">@product.ActualPrice.ToString("C")</h6>
                </div>
            </div>
            </a>
        }
    </section>
</div>

<section class="products-display">
        <div class="best-seller-text"><h5><b>BEST SELLER</b></h5></div>
        <div class="items-list-justify">
            <a href="#" style="color: black;"><h6>All</h6></a>
            @foreach(var category in Model.CurrentCategory){
                <div class="items-list">
                    <a href="#"><h6>@category</h6></a>
                </div>
            }
        </div>
</section>

<!-- Product Display on Body-->
<section>
    <div class="product-wrapper">
        @foreach(var product in Model.Products.OrderBy(x=> Guid.NewGuid()).Take(8))
        {
            <a asp-controller="Product" asp-action="ProductList" asp-route-id="@product.ProductId">
            <div class="pro">
                <img src="./ProductImages/@product.productImageModel.First().imageName" alt="Null" class="other-product-image-body"/>
                <div class="product-below">
                    <div class="product-below-top">
                        <h1>@product.ProductName</h1>
                    </div>
                    <div class="product-below-img">
                        <img src="./images/rate.svg">
                    </div>
                    <div class="product-below-price">
                        <div class="actual-price">@product.Price.ToString("C")</div>
                        <div class="discount-price"><p>@product.ActualPrice.ToString("C")</p></div>
                        <div class="percentage-off">@product.PercentageOff %Off</div>
                    </div>
                </div>
            </div>
            </a>
        }
    </div>
        <div class="load-more">
            <a href="#">LOAD MORE</a>
            <hr />
        </div>
</section>

<section class="blue-section">
    <div class="blue-section-container">
        <div class="blue-section-right">
            <h1>
                Adidas Men Running <br>
                Sneakers
            </h1>   
            <p>Performance and design. Taken right to the edge.<br />SHOP NOW<br />
            <hr/>
            </p>
        </div>
        <div class="blue-section-left">
            <img src="./images/shoe.svg" alt="Shoe"/>
        </div>
    </div>
</section>

<!-- Why Us -->

<section class="why-us">
    <div class="why-us-box">
        
        <div class="why-us-box-header1">
            <img src="./images/shipping.svg"/>
            <h5><b>FREE SHIPPING</b></h5>
        </div>
        <div class="why-us-box-body">
            <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
        </div>
    </div>

    <div class="why-us-box">
        
        <div class="why-us-box-header2">
            <img src="./images/refund.svg"/>
            <h5><b>100% REFUND</b></h5>
        </div>
        <div class="why-us-box-body">
            <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
        </div>
    </div>
    <div class="why-us-box">
        
        <div class="why-us-box-header3">
            <img src="./images/support.svg"/>
            <h5><b>SUPPORT 24/7</b></h5>
        </div>
        <div class="why-us-box-body">
            <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
        </div>
    </div>
</section>

<!-- Latest News -->

<section class="latest-news-container">
    <h4><b>LATEST NEWS</b></h4>
    <div class="latest-news">
        <div class="latest-news-box">
            <div class="latest-news-logo">
                <img src="./images/latestNews1.svg"/>
            </div>
            <div class="latest-news-text">
                <div class="date">
                    <h6>01 Jan, 2015</h6>
                </div>
                <div class="title">
                    <h5>Fashion Industry</h5>
                </div>
                <div class="text">
                    <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
                </div>
            </div>
        </div>

        <div class="latest-news-box">
            <div class="latest-news-logo">
                <img src="./images/latestNews2.svg"/>
            </div>
            <div class="latest-news-text">
                <div class="date">
                    <h6>01 Jan, 2015</h6>
                </div>
                <div class="title">
                    <h5>Best Design Tools</h5>
                </div>
                <div class="text">
                    <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
                </div>
            </div>
        </div>

        <div class="latest-news-box">
            <div class="latest-news-logo">
                <img src="./images/latestNews3.svg"/>
            </div>
            <div class="latest-news-text">
                <div class="date">
                    <h6>01 Jan, 2015</h6>
                </div>
                <div class="title">
                    <h5>HR Community</h5>
                </div>
                <div class="text">
                    <h6>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</h6>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Featured Products -->

<section class="featured-products-container">
    <h4><b>FEATURED PRODUCTS</b></h4>
    <div class="featured-products">
        <div class="featured-products-box">
            <div class="featured-products-img">
                <img src="./images/featured.svg"/>
            </div>
            <div class="featured-products-text">
                <div class="featured-products-name">
                    <h6>Blue Swade Nike Sneakers</h6>
                </div>
                <div class="featured-products-rate">
                    <img src="./images/rate.svg">
                </div>
                <div class="featured-products-price">
                    <div class="featured-product-actual-price">$299,43</div>
                    <div class="featured-product-discount-price"><p>$534,33</p></div>
                </div>
            </div>
        </div>

        <div class="featured-products-box">
            <div class="featured-products-img">
                <img src="./images/featured.svg"/>
            </div>
            <div class="featured-products-text">
                <div class="featured-products-name">
                    <h6>Blue Swade Nike Sneakers</h6>
                </div>
                <div class="featured-products-rate">
                    <img src="./images/rate.svg">
                </div>
                <div class="featured-products-price">
                    <div class="featured-product-actual-price">$299,43</div>
                    <div class="featured-product-discount-price"><p>$534,33</p></div>
                </div>
            </div>
        </div>

        <div class="featured-products-box">
            <div class="featured-products-img">
                <img src="./images/featured.svg"/>
            </div>
            <div class="featured-products-text">
                <div class="featured-products-name">
                    <h6>Blue Swade Nike Sneakers</h6>
                </div>
                <div class="featured-products-rate">
                    <img src="./images/rate.svg">
                </div>
                <div class="featured-products-price">
                    <div class="featured-product-actual-price">$299,43</div>
                    <div class="featured-product-discount-price"><p>$534,33</p></div>
                </div>
            </div>
        </div>
    </div>
</section>

@*Search Bar*@
<section class="search-wrap">
    <div class="search-box">
        <input type="text" class="input" placeholder="Search query..."/>
        <button>SEARCH</button>
    </div>
</section>

ECommerceSystem.MVC/Views/Product/ProductList.cshtml
@model ProductListViewModel

<link rel="stylesheet" href="~/css/details.css" />
<div class="details-navitor">
    <h4 style="color: #33A0FF" class="navigator-label">Home/</h4>
    <h4 style="color: #33A0FF" class="navigator-label">Hot Deal/</h4>
    <h4 class="navigator-label">@Model.currentProduct.ProductName</h4>
</div>
<section id="product-display">
    
    <div id="details-product-main-container">
        
        <div class="details-products">
            <div>
                <div class="details-main-product">
                    <div class="product-images">
                        <img src="~/ProductImages/@Model.currentProduct.productImageModel.First().imageName" class="main-product-image"/>
                        <div class="other-product-images">
                            @foreach(var imageName in Model.currentProduct.productImageModel.Take(4))
                            {
                                <img src="~/ProductImages/@imageName.imageName" class="other-product-image">
                            }
                        </div>
                    </div>
                    <div class="about-product">
                        <h2 class="details-product-title">@Model.currentProduct.ProductName</h2>
                        <div class="product-credentials">
                            <div class="product-stars">
                                <img src="~/Images/star.svg" class="star"/>
                                <img src="~/Images/star.svg" class="star"/>
                                <img src="~/Images/star.svg" class="star"/>
                                <img src="~/Images/star.svg" class="star"/>
                                <img src="~/Images/starEmpty.svg" class="star"/>
                            </div>
                            <h3 class="review-number"> 0 Reviews</h3>
                            <h3 class="review-number" style="color: #33A0FF"> Submit a review</h3>
                        </div>
                        <hr/>
                        <div class="product-price-details">
                            <h6 style="color:#40BFFF" class="product-discount-price">@Model.currentProduct.ActualPrice.ToString("C")</h6>
                            <h6 class="product-original-price">@Model.currentProduct.Price.ToString("C")</h6>
                            <h6 style="color: #FB7181" class="product-discount">@Model.currentProduct.PercentageOff% Off</h6>
                        </div>
                    
                        @if (Model.currentProduct.InStock)
                        {
                            <h4 class="product-summary">Availability: In Stock</h4>
                        }
                        else
                        {
                            <h4 class="product-summary">Availability: Not In Stock</h4>
                        }
                        <div class="product-summary">Category=>
                        
                            @foreach(var category in Model.currentProductCategory)
                            {
                                <h6> ,&nbsp @category </h6>;
                            }
                        </div>
                        <h4 class="product-summary">Free shipping</h4>
                            <hr/>
                        <div class="colour-selection">
                            <h4 class="colour-header">Select Colour</h4>
                            <div class="colours">
                                <img src="~/Images/blue.svg" class="single-color"/>
                                <img src="~/Images/red.svg" class="single-color"/>
                                <img src="~/Images/black.svg" class="single-color"/>
                                <img src="~/Images/yellow.svg" class="single-color"/>
                            </div>
                        </div>
                        <div class="size">
                            <div>
                                <h4 class="size-label">Size</h4>
                            </div>
                            <div class="div__sel">
                                <Select>
                                    <option class="curr">XL</option>
                                    <option class="curr">M</option>
                                    <option class="curr">L</option>
                                    <option class="curr">XXL</option>
                                </Select>
                            </div>
                        </div>
                        <hr/>
                        <div class="wrapper-main">
                            <div class="wrapper">
                                <span class="minus">-</span>
                                <span class="num">1</span>
                                <span class="plus">+</span>
                            </div>
                            <div class="wrapper-main-sub">
                                <div class="add-to-cat">
                                    <span class="minus"><img src="~/images/cart2.svg" /></span>
                                    <span class="plus">Add To Cart</span>
                                </div>
                                <div class="add-to-cat-save">
                                    <span class="minus-save"><img src="~/images/heart.svg" /></span>
                                </div>
                            </div>
                        </div>
                        <hr/>
                    </div>
                </div>
                <div class="product-description">
                    <div>
                        <h5>Product Information</h5>
                        <hr />
                    </div>
                    <p>
                        @Model.currentProduct.LongDescription
                    </p>
                </div>
            </div>
            <div class="details-best-seller-product">
                <h4 style="text-align: left;" class="details-best-seller-title">BEST SELLER</h4>
                <img src="~/images/product9.png" class="details-best-seller-image"/>
                <div class="best-seller-product-stars">
                    <img src="~/Images/star.svg" class="star"/>
                    <img src="~/Images/star.svg" class="star"/>
                    <img src="~/Images/star.svg" class="star"/>
                    <img src="~/Images/star.svg" class="star"/>
                    <img src="~/Images/star.svg" class="star"/>
                </div>
                <div class="best-seller-price-details">
                    <h3 class="details-best-seller-discount-price">$499</h3>
                    <h3 class="details-best-seller-original-price">$599$</h3>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="products-display">
   <div class="best-seller-text"><h5><b>RELATED PRODUCTS</b></h5></div>
</section>

<!-- Product Display on Banner -->
<section>
    <div class="product-wrapper">
        @foreach(var product in Model.AllRelatedProductsByCategory.OrderBy(x=> Guid.NewGuid()).Take(4))
        {
            <a asp-controller="Product" asp-action="ProductList" asp-route-id="@product.ProductId">
            <div class="pro">
                <img src="~/ProductImages/@product.productImageModel.First().imageName" alt="Null" class="other-product-image-body"/>
                <div class="product-below">
                    <div class="product-below-top">
                        <h1>@product.ProductName</h1>
                    </div>
                    <div class="product-below-img">
                        <img src="~/images/rate.svg">
                    </div>
                    <div class="product-below-price">
                        <div class="actual-price">@product.Price.ToString("C")</div>
                        <div class="discount-price"><p>@product.ActualPrice.ToString("C")</p></div>
                        <div class="percentage-off">@product.PercentageOff %Off</div>
                    </div>
                </div>
            </div>
            </a>
        }
    </div>
</section>

        @*<div>
            <h4>@Model.currentProduct.ShortDescription</h4>
            <h4>@Model.currentProduct.Quantity</h4>
        </div>*@